### YamlMime:ManagedReference
items:
- uid: Rudeus.Application
  commentId: N:Rudeus.Application
  id: Rudeus.Application
  children:
  - Rudeus.Application.TaskTrayForm
  langs:
  - csharp
  - vb
  name: Rudeus.Application
  nameWithType: Rudeus.Application
  fullName: Rudeus.Application
  type: Namespace
  assemblies:
  - Application
references:
- uid: Rudeus.Application.TaskTrayForm
  commentId: T:Rudeus.Application.TaskTrayForm
  href: Rudeus.Application.TaskTrayForm.html
  name: TaskTrayForm
  nameWithType: TaskTrayForm
  fullName: Rudeus.Application.TaskTrayForm
