### YamlMime:ManagedReference
items:
- uid: Test.SharedLib.Model.Settings
  commentId: N:Test.SharedLib.Model.Settings
  id: Test.SharedLib.Model.Settings
  children:
  - Test.SharedLib.Model.Settings.AppSettingsTest
  - Test.SharedLib.Model.Settings.FakeSettings
  - Test.SharedLib.Model.Settings.FakeSettingsTest
  - Test.SharedLib.Model.Settings.RootSettingsTest
  langs:
  - csharp
  - vb
  name: Test.SharedLib.Model.Settings
  nameWithType: Test.SharedLib.Model.Settings
  fullName: Test.SharedLib.Model.Settings
  type: Namespace
  assemblies:
  - Test
references:
- uid: Test.SharedLib.Model.Settings.AppSettingsTest
  commentId: T:Test.SharedLib.Model.Settings.AppSettingsTest
  href: Test.SharedLib.Model.Settings.AppSettingsTest.html
  name: AppSettingsTest
  nameWithType: AppSettingsTest
  fullName: Test.SharedLib.Model.Settings.AppSettingsTest
- uid: Test.SharedLib.Model.Settings.FakeSettings
  commentId: T:Test.SharedLib.Model.Settings.FakeSettings
  href: Test.SharedLib.Model.Settings.FakeSettings.html
  name: FakeSettings
  nameWithType: FakeSettings
  fullName: Test.SharedLib.Model.Settings.FakeSettings
- uid: Test.SharedLib.Model.Settings.FakeSettingsTest
  commentId: T:Test.SharedLib.Model.Settings.FakeSettingsTest
  href: Test.SharedLib.Model.Settings.FakeSettingsTest.html
  name: FakeSettingsTest
  nameWithType: FakeSettingsTest
  fullName: Test.SharedLib.Model.Settings.FakeSettingsTest
- uid: Test.SharedLib.Model.Settings.RootSettingsTest
  commentId: T:Test.SharedLib.Model.Settings.RootSettingsTest
  href: Test.SharedLib.Model.Settings.RootSettingsTest.html
  name: RootSettingsTest
  nameWithType: RootSettingsTest
  fullName: Test.SharedLib.Model.Settings.RootSettingsTest
