name: File Counter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download cloc
      run: wget https://github.com/AlDanial/cloc/releases/download/v1.98/cloc-1.98.pl

    - name: Add execute permission
      run: chmod +x cloc-1.98.pl

    - name: Run cloc
      run: ./cloc-1.98.pl .
