name: Version

on:
  workflow_dispatch:
    inputs:
      semantic:
        description: Semantic versioning
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
      target:
        description: Target
        required: true
        default: Command
        type: choice
        options:
          - Command
          - Application

jobs:
  version-up:
    runs-on: ubuntu-20.04
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
      - name: Version up
        id: version
        run: |
          set -x
          ruby ./bump_version.rb -d ${{ github.event.inputs.target }} --${{ github.event.inputs.semantic }}
        env:
          SEMANTIC: ${{ github.event.inputs.semantic }}
      - name: Commit & PR
        run: |
          set -x
          version=$(cat Command/version.txt)
          branch="release/${{ github.event.inputs.target }}/${version}"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git switch -c ${branch}
          git add .
          git commit -m "更新 ${{ github.event.inputs.target }} ${version}"
          git push origin ${branch}
          gh pr create --base ${GITHUB_REF_NAME} --head ${branch} --assignee ${GITHUB_ACTOR} --title ${version} --body ''
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ github.token }}
